### ISSUE TITLE
Does this support Windows?

### ISSUE THREAD

**Issue by chaoscreater** [shanginn/git-aicommit#8]
Got it installed, but it complains about this on Windows:

```
fatal: ':(exclude)*.lock': '':(exclude)*.lock'' is outside repository at 'D:/Documents/exampleProject'
node:internal/errors:867
  const err = new Error(message);
```

**Comment by shanginn** [comment]
sorry brother, I don't have a Windows machine to test it on.

[this is](https://github.com/shanginn/git-aicommit/blob/master/autocommit.js#L49) the place where diff command is constructed. try to `console.log(diffCommand)` (or debug) to see the command and run it in the terminal to see what's going on

**Comment by shanginn** [comment]
maybe try to set excludeFromDiff to an empty array in your config file

[read more about RC files](https://www.npmjs.com/package/rc?activeTab=readme)
